version: "3.7"
services:

  webserver:
    container_name: www-refund
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOCKER=1
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    ports:
      - "8087:80"
    volumes:
      - .:/var/www/html
